package com.bolehunt.gene.persistence;

import com.bolehunt.gene.domain.BasicInfo;
import com.bolehunt.gene.domain.BasicInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int countByExample(BasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int deleteByExample(BasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int insert(BasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int insertSelective(BasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    List<BasicInfo> selectByExample(BasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    BasicInfo selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") BasicInfo record, @Param("example") BasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int updateByExample(@Param("record") BasicInfo record, @Param("example") BasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int updateByPrimaryKeySelective(BasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_info
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int updateByPrimaryKey(BasicInfo record);
}