package com.bolehunt.gene.persistence;

import com.bolehunt.gene.domain.Education;
import com.bolehunt.gene.domain.EducationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EducationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    int countByExample(EducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    int deleteByExample(EducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    int insert(Education record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    int insertSelective(Education record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    List<Education> selectByExample(EducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    Education selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    int updateByExampleSelective(@Param("record") Education record, @Param("example") EducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    int updateByExample(@Param("record") Education record, @Param("example") EducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    int updateByPrimaryKeySelective(Education record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    int updateByPrimaryKey(Education record);
}