package com.bolehunt.gene.persistence;

import com.bolehunt.gene.domain.Experience;
import com.bolehunt.gene.domain.ExperienceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExperienceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int countByExample(ExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int deleteByExample(ExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int insert(Experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int insertSelective(Experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    List<Experience> selectByExample(ExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    Experience selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") Experience record, @Param("example") ExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int updateByExample(@Param("record") Experience record, @Param("example") ExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int updateByPrimaryKeySelective(Experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int updateByPrimaryKey(Experience record);
}