package com.bolehunt.gene.persistence;

import com.bolehunt.gene.domain.Sex;
import com.bolehunt.gene.domain.SexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int countByExample(SexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int deleteByExample(SexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int insert(Sex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int insertSelective(Sex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    List<Sex> selectByExample(SexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    Sex selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") Sex record, @Param("example") SexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int updateByExample(@Param("record") Sex record, @Param("example") SexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int updateByPrimaryKeySelective(Sex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    int updateByPrimaryKey(Sex record);
}