package com.bolehunt.gene.persistence;

import com.bolehunt.gene.domain.SystemParam;
import com.bolehunt.gene.domain.SystemParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_PARAM
     *
     * @mbggenerated
     */
    int countByExample(SystemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_PARAM
     *
     * @mbggenerated
     */
    int deleteByExample(SystemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_PARAM
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_PARAM
     *
     * @mbggenerated
     */
    int insert(SystemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_PARAM
     *
     * @mbggenerated
     */
    int insertSelective(SystemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_PARAM
     *
     * @mbggenerated
     */
    List<SystemParam> selectByExample(SystemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_PARAM
     *
     * @mbggenerated
     */
    SystemParam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_PARAM
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemParam record, @Param("example") SystemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_PARAM
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemParam record, @Param("example") SystemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_PARAM
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_PARAM
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemParam record);
}