package com.bolehunt.gene.persistence;

import com.bolehunt.gene.domain.VerifyToken;
import com.bolehunt.gene.domain.VerifyTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VerifyTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_token
     *
     * @mbggenerated
     */
    int countByExample(VerifyTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_token
     *
     * @mbggenerated
     */
    int deleteByExample(VerifyTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_token
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_token
     *
     * @mbggenerated
     */
    int insert(VerifyToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_token
     *
     * @mbggenerated
     */
    int insertSelective(VerifyToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_token
     *
     * @mbggenerated
     */
    List<VerifyToken> selectByExample(VerifyTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_token
     *
     * @mbggenerated
     */
    VerifyToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_token
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") VerifyToken record, @Param("example") VerifyTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_token
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") VerifyToken record, @Param("example") VerifyTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VerifyToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VerifyToken record);
}