package com.bolehunt.gene.persistence;

import com.bolehunt.gene.domain.WorkExperience;
import com.bolehunt.gene.domain.WorkExperienceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkExperienceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_exp
     *
     * @mbggenerated
     */
    int countByExample(WorkExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_exp
     *
     * @mbggenerated
     */
    int deleteByExample(WorkExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_exp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_exp
     *
     * @mbggenerated
     */
    int insert(WorkExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_exp
     *
     * @mbggenerated
     */
    int insertSelective(WorkExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_exp
     *
     * @mbggenerated
     */
    List<WorkExperience> selectByExample(WorkExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_exp
     *
     * @mbggenerated
     */
    WorkExperience selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_exp
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WorkExperience record, @Param("example") WorkExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_exp
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WorkExperience record, @Param("example") WorkExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_exp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WorkExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_exp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WorkExperience record);
}