package com.bolehunt.gene.domain;

public class BasicInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_info.user_id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_info.name
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_info.country_id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    private Integer countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_info.city
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_info.tel_no
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    private String telNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_info.exp_id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    private Integer expId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_info.degree_id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    private Integer degreeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_info.sex_id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    private Integer sexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_info.born_year
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    private Integer bornYear;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_info.user_id
     *
     * @return the value of basic_info.user_id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_info.user_id
     *
     * @param userId the value for basic_info.user_id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_info.name
     *
     * @return the value of basic_info.name
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_info.name
     *
     * @param name the value for basic_info.name
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_info.country_id
     *
     * @return the value of basic_info.country_id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public Integer getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_info.country_id
     *
     * @param countryId the value for basic_info.country_id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_info.city
     *
     * @return the value of basic_info.city
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_info.city
     *
     * @param city the value for basic_info.city
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_info.tel_no
     *
     * @return the value of basic_info.tel_no
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_info.tel_no
     *
     * @param telNo the value for basic_info.tel_no
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo == null ? null : telNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_info.exp_id
     *
     * @return the value of basic_info.exp_id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public Integer getExpId() {
        return expId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_info.exp_id
     *
     * @param expId the value for basic_info.exp_id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public void setExpId(Integer expId) {
        this.expId = expId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_info.degree_id
     *
     * @return the value of basic_info.degree_id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public Integer getDegreeId() {
        return degreeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_info.degree_id
     *
     * @param degreeId the value for basic_info.degree_id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public void setDegreeId(Integer degreeId) {
        this.degreeId = degreeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_info.sex_id
     *
     * @return the value of basic_info.sex_id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public Integer getSexId() {
        return sexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_info.sex_id
     *
     * @param sexId the value for basic_info.sex_id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public void setSexId(Integer sexId) {
        this.sexId = sexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_info.born_year
     *
     * @return the value of basic_info.born_year
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public Integer getBornYear() {
        return bornYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_info.born_year
     *
     * @param bornYear the value for basic_info.born_year
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public void setBornYear(Integer bornYear) {
        this.bornYear = bornYear;
    }
}