package com.bolehunt.gene.domain;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_id
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.chi_name
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    private String chiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.eng_name
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    private String engName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.website
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.intro
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.location
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_id
     *
     * @return the value of company.company_id
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_id
     *
     * @param companyId the value for company.company_id
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.chi_name
     *
     * @return the value of company.chi_name
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public String getChiName() {
        return chiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.chi_name
     *
     * @param chiName the value for company.chi_name
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public void setChiName(String chiName) {
        this.chiName = chiName == null ? null : chiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.eng_name
     *
     * @return the value of company.eng_name
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public String getEngName() {
        return engName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.eng_name
     *
     * @param engName the value for company.eng_name
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public void setEngName(String engName) {
        this.engName = engName == null ? null : engName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.website
     *
     * @return the value of company.website
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.website
     *
     * @param website the value for company.website
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.intro
     *
     * @return the value of company.intro
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.intro
     *
     * @param intro the value for company.intro
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.location
     *
     * @return the value of company.location
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.location
     *
     * @param location the value for company.location
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }
}