package com.bolehunt.gene.domain;

public class Country {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.country_name
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    private String countryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.country_name_eng
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    private String countryNameEng;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.id
     *
     * @return the value of country.id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.id
     *
     * @param id the value for country.id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.country_name
     *
     * @return the value of country.country_name
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.country_name
     *
     * @param countryName the value for country.country_name
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName == null ? null : countryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.country_name_eng
     *
     * @return the value of country.country_name_eng
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public String getCountryNameEng() {
        return countryNameEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.country_name_eng
     *
     * @param countryNameEng the value for country.country_name_eng
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public void setCountryNameEng(String countryNameEng) {
        this.countryNameEng = countryNameEng == null ? null : countryNameEng.trim();
    }
}