package com.bolehunt.gene.domain;

public class Education {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.id
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.user_id
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.school_name
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.degree_id
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    private Integer degreeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.start_year
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    private Integer startYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.end_year
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    private Integer endYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.department
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    private String department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.id
     *
     * @return the value of education.id
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.id
     *
     * @param id the value for education.id
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.user_id
     *
     * @return the value of education.user_id
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.user_id
     *
     * @param userId the value for education.user_id
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.school_name
     *
     * @return the value of education.school_name
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.school_name
     *
     * @param schoolName the value for education.school_name
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.degree_id
     *
     * @return the value of education.degree_id
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    public Integer getDegreeId() {
        return degreeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.degree_id
     *
     * @param degreeId the value for education.degree_id
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    public void setDegreeId(Integer degreeId) {
        this.degreeId = degreeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.start_year
     *
     * @return the value of education.start_year
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    public Integer getStartYear() {
        return startYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.start_year
     *
     * @param startYear the value for education.start_year
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    public void setStartYear(Integer startYear) {
        this.startYear = startYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.end_year
     *
     * @return the value of education.end_year
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    public Integer getEndYear() {
        return endYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.end_year
     *
     * @param endYear the value for education.end_year
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    public void setEndYear(Integer endYear) {
        this.endYear = endYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.department
     *
     * @return the value of education.department
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.department
     *
     * @param department the value for education.department
     *
     * @mbggenerated Thu Jul 23 21:52:10 CST 2015
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }
}