package com.bolehunt.gene.domain;

import java.io.Serializable;

public class Education implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.basic_info_id
     *
     * @mbggenerated
     */
    private Integer basicInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.school_name
     *
     * @mbggenerated
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.degree
     *
     * @mbggenerated
     */
    private Integer degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.start_year
     *
     * @mbggenerated
     */
    private Integer startYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.end_year
     *
     * @mbggenerated
     */
    private Integer endYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education.department
     *
     * @mbggenerated
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table education
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.id
     *
     * @return the value of education.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.id
     *
     * @param id the value for education.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.basic_info_id
     *
     * @return the value of education.basic_info_id
     *
     * @mbggenerated
     */
    public Integer getBasicInfoId() {
        return basicInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.basic_info_id
     *
     * @param basicInfoId the value for education.basic_info_id
     *
     * @mbggenerated
     */
    public void setBasicInfoId(Integer basicInfoId) {
        this.basicInfoId = basicInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.school_name
     *
     * @return the value of education.school_name
     *
     * @mbggenerated
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.school_name
     *
     * @param schoolName the value for education.school_name
     *
     * @mbggenerated
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.degree
     *
     * @return the value of education.degree
     *
     * @mbggenerated
     */
    public Integer getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.degree
     *
     * @param degree the value for education.degree
     *
     * @mbggenerated
     */
    public void setDegree(Integer degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.start_year
     *
     * @return the value of education.start_year
     *
     * @mbggenerated
     */
    public Integer getStartYear() {
        return startYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.start_year
     *
     * @param startYear the value for education.start_year
     *
     * @mbggenerated
     */
    public void setStartYear(Integer startYear) {
        this.startYear = startYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.end_year
     *
     * @return the value of education.end_year
     *
     * @mbggenerated
     */
    public Integer getEndYear() {
        return endYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.end_year
     *
     * @param endYear the value for education.end_year
     *
     * @mbggenerated
     */
    public void setEndYear(Integer endYear) {
        this.endYear = endYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education.department
     *
     * @return the value of education.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education.department
     *
     * @param department the value for education.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }
}