package com.bolehunt.gene.domain;

public class Experience {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experience.id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experience.exp_desc
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    private String expDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experience.id
     *
     * @return the value of experience.id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experience.id
     *
     * @param id the value for experience.id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experience.exp_desc
     *
     * @return the value of experience.exp_desc
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public String getExpDesc() {
        return expDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experience.exp_desc
     *
     * @param expDesc the value for experience.exp_desc
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public void setExpDesc(String expDesc) {
        this.expDesc = expDesc == null ? null : expDesc.trim();
    }
}