package com.bolehunt.gene.domain;

import java.util.Date;

public class Post {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_id
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    private Integer postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.company_id
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.user_id
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_desc
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    private String postDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_date
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    private Date postDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.location
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.salary_min
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    private Integer salaryMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.salary_max
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    private Integer salaryMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.work_year_min
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    private Integer workYearMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.work_year_max
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    private Integer workYearMax;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_id
     *
     * @return the value of post.post_id
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_id
     *
     * @param postId the value for post.post_id
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.company_id
     *
     * @return the value of post.company_id
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.company_id
     *
     * @param companyId the value for post.company_id
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.user_id
     *
     * @return the value of post.user_id
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.user_id
     *
     * @param userId the value for post.user_id
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_desc
     *
     * @return the value of post.post_desc
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public String getPostDesc() {
        return postDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_desc
     *
     * @param postDesc the value for post.post_desc
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public void setPostDesc(String postDesc) {
        this.postDesc = postDesc == null ? null : postDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_date
     *
     * @return the value of post.post_date
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public Date getPostDate() {
        return postDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_date
     *
     * @param postDate the value for post.post_date
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.location
     *
     * @return the value of post.location
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.location
     *
     * @param location the value for post.location
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.salary_min
     *
     * @return the value of post.salary_min
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public Integer getSalaryMin() {
        return salaryMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.salary_min
     *
     * @param salaryMin the value for post.salary_min
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public void setSalaryMin(Integer salaryMin) {
        this.salaryMin = salaryMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.salary_max
     *
     * @return the value of post.salary_max
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public Integer getSalaryMax() {
        return salaryMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.salary_max
     *
     * @param salaryMax the value for post.salary_max
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public void setSalaryMax(Integer salaryMax) {
        this.salaryMax = salaryMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.work_year_min
     *
     * @return the value of post.work_year_min
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public Integer getWorkYearMin() {
        return workYearMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.work_year_min
     *
     * @param workYearMin the value for post.work_year_min
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public void setWorkYearMin(Integer workYearMin) {
        this.workYearMin = workYearMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.work_year_max
     *
     * @return the value of post.work_year_max
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public Integer getWorkYearMax() {
        return workYearMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.work_year_max
     *
     * @param workYearMax the value for post.work_year_max
     *
     * @mbggenerated Fri May 29 22:54:59 CST 2015
     */
    public void setWorkYearMax(Integer workYearMax) {
        this.workYearMax = workYearMax;
    }
}