package com.bolehunt.gene.domain;

public class Sex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sex.id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sex.sex_desc
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    private String sexDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sex.id
     *
     * @return the value of sex.id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sex.id
     *
     * @param id the value for sex.id
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sex.sex_desc
     *
     * @return the value of sex.sex_desc
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public String getSexDesc() {
        return sexDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sex.sex_desc
     *
     * @param sexDesc the value for sex.sex_desc
     *
     * @mbggenerated Wed Jul 15 21:55:19 CST 2015
     */
    public void setSexDesc(String sexDesc) {
        this.sexDesc = sexDesc == null ? null : sexDesc.trim();
    }
}