package com.bolehunt.gene.domain;

import java.io.Serializable;

public class SystemParam implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAM.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAM.param_group
     *
     * @mbggenerated
     */
    private String paramGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAM.param_value
     *
     * @mbggenerated
     */
    private Integer paramValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAM.param_desc_chi
     *
     * @mbggenerated
     */
    private String paramDescChi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAM.param_desc_eng
     *
     * @mbggenerated
     */
    private String paramDescEng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAM.enabled
     *
     * @mbggenerated
     */
    private Integer enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSTEM_PARAM
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAM.id
     *
     * @return the value of SYSTEM_PARAM.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAM.id
     *
     * @param id the value for SYSTEM_PARAM.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAM.param_group
     *
     * @return the value of SYSTEM_PARAM.param_group
     *
     * @mbggenerated
     */
    public String getParamGroup() {
        return paramGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAM.param_group
     *
     * @param paramGroup the value for SYSTEM_PARAM.param_group
     *
     * @mbggenerated
     */
    public void setParamGroup(String paramGroup) {
        this.paramGroup = paramGroup == null ? null : paramGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAM.param_value
     *
     * @return the value of SYSTEM_PARAM.param_value
     *
     * @mbggenerated
     */
    public Integer getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAM.param_value
     *
     * @param paramValue the value for SYSTEM_PARAM.param_value
     *
     * @mbggenerated
     */
    public void setParamValue(Integer paramValue) {
        this.paramValue = paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAM.param_desc_chi
     *
     * @return the value of SYSTEM_PARAM.param_desc_chi
     *
     * @mbggenerated
     */
    public String getParamDescChi() {
        return paramDescChi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAM.param_desc_chi
     *
     * @param paramDescChi the value for SYSTEM_PARAM.param_desc_chi
     *
     * @mbggenerated
     */
    public void setParamDescChi(String paramDescChi) {
        this.paramDescChi = paramDescChi == null ? null : paramDescChi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAM.param_desc_eng
     *
     * @return the value of SYSTEM_PARAM.param_desc_eng
     *
     * @mbggenerated
     */
    public String getParamDescEng() {
        return paramDescEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAM.param_desc_eng
     *
     * @param paramDescEng the value for SYSTEM_PARAM.param_desc_eng
     *
     * @mbggenerated
     */
    public void setParamDescEng(String paramDescEng) {
        this.paramDescEng = paramDescEng == null ? null : paramDescEng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAM.enabled
     *
     * @return the value of SYSTEM_PARAM.enabled
     *
     * @mbggenerated
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAM.enabled
     *
     * @param enabled the value for SYSTEM_PARAM.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }
}