package com.bolehunt.gene.domain;

import java.io.Serializable;

public class SystemParam implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_param.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_param.param_key
     *
     * @mbggenerated
     */
    private String paramKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_param.param_value
     *
     * @mbggenerated
     */
    private Integer paramValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_param.param_desc
     *
     * @mbggenerated
     */
    private String paramDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_param.enabled
     *
     * @mbggenerated
     */
    private Integer enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_param
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_param.id
     *
     * @return the value of system_param.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_param.id
     *
     * @param id the value for system_param.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_param.param_key
     *
     * @return the value of system_param.param_key
     *
     * @mbggenerated
     */
    public String getParamKey() {
        return paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_param.param_key
     *
     * @param paramKey the value for system_param.param_key
     *
     * @mbggenerated
     */
    public void setParamKey(String paramKey) {
        this.paramKey = paramKey == null ? null : paramKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_param.param_value
     *
     * @return the value of system_param.param_value
     *
     * @mbggenerated
     */
    public Integer getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_param.param_value
     *
     * @param paramValue the value for system_param.param_value
     *
     * @mbggenerated
     */
    public void setParamValue(Integer paramValue) {
        this.paramValue = paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_param.param_desc
     *
     * @return the value of system_param.param_desc
     *
     * @mbggenerated
     */
    public String getParamDesc() {
        return paramDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_param.param_desc
     *
     * @param paramDesc the value for system_param.param_desc
     *
     * @mbggenerated
     */
    public void setParamDesc(String paramDesc) {
        this.paramDesc = paramDesc == null ? null : paramDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_param.enabled
     *
     * @return the value of system_param.enabled
     *
     * @mbggenerated
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_param.enabled
     *
     * @param enabled the value for system_param.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }
}