package com.bolehunt.gene.domain;

import java.io.Serializable;
import java.util.Date;

public class VerifyToken implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_token.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_token.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_token.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_token.token_type
     *
     * @mbggenerated
     */
    private Integer tokenType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_token.expiry_date
     *
     * @mbggenerated
     */
    private Date expiryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_token.sent
     *
     * @mbggenerated
     */
    private Integer sent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_token.verified
     *
     * @mbggenerated
     */
    private Integer verified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table verify_token
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_token.id
     *
     * @return the value of verify_token.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_token.id
     *
     * @param id the value for verify_token.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_token.user_id
     *
     * @return the value of verify_token.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_token.user_id
     *
     * @param userId the value for verify_token.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_token.token
     *
     * @return the value of verify_token.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_token.token
     *
     * @param token the value for verify_token.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_token.token_type
     *
     * @return the value of verify_token.token_type
     *
     * @mbggenerated
     */
    public Integer getTokenType() {
        return tokenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_token.token_type
     *
     * @param tokenType the value for verify_token.token_type
     *
     * @mbggenerated
     */
    public void setTokenType(Integer tokenType) {
        this.tokenType = tokenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_token.expiry_date
     *
     * @return the value of verify_token.expiry_date
     *
     * @mbggenerated
     */
    public Date getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_token.expiry_date
     *
     * @param expiryDate the value for verify_token.expiry_date
     *
     * @mbggenerated
     */
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_token.sent
     *
     * @return the value of verify_token.sent
     *
     * @mbggenerated
     */
    public Integer getSent() {
        return sent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_token.sent
     *
     * @param sent the value for verify_token.sent
     *
     * @mbggenerated
     */
    public void setSent(Integer sent) {
        this.sent = sent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_token.verified
     *
     * @return the value of verify_token.verified
     *
     * @mbggenerated
     */
    public Integer getVerified() {
        return verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_token.verified
     *
     * @param verified the value for verify_token.verified
     *
     * @mbggenerated
     */
    public void setVerified(Integer verified) {
        this.verified = verified;
    }
}