package com.bolehunt.gene.domain;

import java.io.Serializable;

public class WorkExperience implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_exp.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_exp.basic_info_id
     *
     * @mbggenerated
     */
    private Integer basicInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_exp.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_exp.start_year
     *
     * @mbggenerated
     */
    private Integer startYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_exp.end_year
     *
     * @mbggenerated
     */
    private Integer endYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_exp.position_name
     *
     * @mbggenerated
     */
    private String positionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_exp.position_desc
     *
     * @mbggenerated
     */
    private String positionDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_exp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_exp.id
     *
     * @return the value of work_exp.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_exp.id
     *
     * @param id the value for work_exp.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_exp.basic_info_id
     *
     * @return the value of work_exp.basic_info_id
     *
     * @mbggenerated
     */
    public Integer getBasicInfoId() {
        return basicInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_exp.basic_info_id
     *
     * @param basicInfoId the value for work_exp.basic_info_id
     *
     * @mbggenerated
     */
    public void setBasicInfoId(Integer basicInfoId) {
        this.basicInfoId = basicInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_exp.company_name
     *
     * @return the value of work_exp.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_exp.company_name
     *
     * @param companyName the value for work_exp.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_exp.start_year
     *
     * @return the value of work_exp.start_year
     *
     * @mbggenerated
     */
    public Integer getStartYear() {
        return startYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_exp.start_year
     *
     * @param startYear the value for work_exp.start_year
     *
     * @mbggenerated
     */
    public void setStartYear(Integer startYear) {
        this.startYear = startYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_exp.end_year
     *
     * @return the value of work_exp.end_year
     *
     * @mbggenerated
     */
    public Integer getEndYear() {
        return endYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_exp.end_year
     *
     * @param endYear the value for work_exp.end_year
     *
     * @mbggenerated
     */
    public void setEndYear(Integer endYear) {
        this.endYear = endYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_exp.position_name
     *
     * @return the value of work_exp.position_name
     *
     * @mbggenerated
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_exp.position_name
     *
     * @param positionName the value for work_exp.position_name
     *
     * @mbggenerated
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_exp.position_desc
     *
     * @return the value of work_exp.position_desc
     *
     * @mbggenerated
     */
    public String getPositionDesc() {
        return positionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_exp.position_desc
     *
     * @param positionDesc the value for work_exp.position_desc
     *
     * @mbggenerated
     */
    public void setPositionDesc(String positionDesc) {
        this.positionDesc = positionDesc == null ? null : positionDesc.trim();
    }
}